[package]
name = "Alacritty-Hotkey-Launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev = "0.5.0"
x11 = "2.21.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde_json = "1.0"

[dev-dependencies]
tempfile = "3"
