name: Release Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rust
        run: |
          sudo apt update && sudo apt upgrade -y
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          source $HOME/.cargo/env

      - name: Build release package
        run: |
          cargo build --release
